project_id = "zgftlstpklquhpfwiadz"

[functions.chat]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.send-purchase-email]
verify_jwt = true

[functions.send-notification]
verify_jwt = false
